config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :advertisers do
          collection do
              post :selected
          end
    end
    resources :advertises  do
         collection do
              post :selected           
        end
    end
    resources :advocates  do
         collection do
              post :selected           
        end
    end
    resources :tasks  do
         collection do
              post :selected           
        end
    end
    resources :informations   do
         collection do
              post :selected           
        end
    end
  end
  devise_for :advertisers
  resources :advertises

  resources :advocates
  resources :advertiseapis
  resources :beaconapis

  root to: redirect('/advertises')

end

app/models/advertise.rb
class Advertise < ActiveRecord::Base
	belongs_to :advertiser
end

app/models/advertiser.rb
class Advertiser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :advertises
end

app/models/advocate.rb
class Advocate < ActiveRecord::Base
end

app/models/information.rb
class Information < ActiveRecord::Base
end

app/models/message.rb
class Message < ActiveRecord::Base
end

app/models/task.rb
class Task < ActiveRecord::Base
end

app/controllers/admin/informations_controller.rb
class Admin::InformationsController < ApplicationController
	before_action :authenticate
              layout "adminapplication"

    def index
		
	end
    def selected
		if params[:keyword].empty?
			@information = Information.all
							
		else 
			@information = Information.where(["#{params[:option]} like?","%#{params[:keyword]}%"])
						
		end
	end
 def show
     		information = Information.find(params[:id])
		@information = information.advertiser
		 
	end
def edits
   		@information = Information.find(params[:id])
	end
    def update
  		@information = Information.find(params[:id])
  		@information.update(information_params)

  		redirect_to :action => :index
	end
   def destroy
  		@information = Information.find(params[:id])
  		@information.destroy

  		 redirect_to :action => :index
	end	
    # ....

    protected

    def authenticate
       authenticate_or_request_with_http_basic do |user_name, password|
           user_name == "username" && password == "password"
       end
    end

 private

    def information_params
   params.require(:information).permit(:name, :email, :advertiser_id, :phone, :account, :password, :count)
end
end

app/controllers/advertiseapis_controller.rb
class AdvertiseapisController < ApplicationController
	 def index

		@advertises = Advertise.all.select("title","end_date_time","location")
		render :json =>@advertises
	end
   
end

app/controllers/advertises_controller.rb
class AdvertisesController < ApplicationController
before_action :authenticate_advertiser!  
	def index
		@advertise = Advertise.where(:advertiser_id => current_advertiser.id)
	end
       def new
              @advertise = Advertise.new
       end
	def create
  
             @advertise = Advertise.new(advertise_params)
             @advertise.advertiser_id = current_advertiser.id
             @advertise.save

             redirect_to :action => :index
      end
      def show
            @advertise = Advertise.find(params[:id])
      end
      def edit
      end

private
      def advertise_params
          
            params.require(:advertise).permit(:title, :content, :start_date_time, :end_date_time, :location, :max_number)


      end

end

app/controllers/advocates_controller.rb
class AdvocatesController < ApplicationController
	
	def index

		 @advocate=Advocate.find_by_account(params[:account])
		 if @advocate==nil
		 	render :json => Message.find_by_id(3)
		else
		 	
			if params[:password] == @advocate.password
		     
                             	 render :json => Message.find_by_id(1)
			else
		     	render :json => Message.find_by_id(2)

			end
		end
	end
	
	def create
		@advocate = Advocate.new(:name => params[:name],:account => params[:account],:password => params[:password],:email => params[:email],:phone => params[:phone])
		@advocate.save
	end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  #protect_from_forgery with: :exception
  #before_action :authenticate_advertiser!
end

app/controllers/beaconapis_controller.rb
class BeaconapisController < ApplicationController
end

app/controllers/information_controller.rb
class InformationController < ApplicationController
end

app/helpers/admin/advertises_helper.rb
module Admin::AdvertisesHelper
end

app/helpers/admin/advocates_helper.rb
module Admin::AdvocatesHelper
end

app/helpers/admin/informations_helper.rb
module Admin::InformationsHelper
end

app/helpers/admin/tasks_helper.rb
module Admin::TasksHelper
end

app/helpers/advertise_helper.rb
module AdvertiseHelper
end

app/helpers/advertiseapi_helper.rb
module AdvertiseapiHelper
end

app/helpers/advertiseapis_helper.rb
module AdvertiseapisHelper
end

app/helpers/advocate_helper.rb
module AdvocateHelper
end

app/helpers/advocates_helper.rb
module AdvocatesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beaconapis_helper.rb
module BeaconapisHelper
end

app/helpers/information_helper.rb
module InformationHelper
end

app/views/admin/informations/edit.html.erb
<%= form_for @advertisers, :url => { :controller => 'advertisers', :action => 'update', :id => @advertisers } do |f| %>
    <%= f.label :name, "Name" %>
    <%= f.text_field :name %>
    <%= f.label :name, "Advertiser_id" %>
    <%= f.text_field :advertiser_id %>
     <%= f.label :name, "Email" %>
    <%= f.text_field :email %>
    <%= f.label :name, "phone" %>
    <%= f.text_field :phone %>
    <%= f.label :name, "Account" %>
    <%= f.text_field :account %>
    <%= f.label :name, "Password" %>
    <%= f.text_field :password %>
    <%= f.label :name, "Count" %>
    <%= f.text_field :count %>
    
    <%= f.submit "Update" %>
<% end %>

app/views/admin/informations/index.html.erb
<%= form_tag selected_admin_informations_path do %>
<%= select_tag(:option, options_for_select([['information_id', 'information_id'], ['advertise_id', 'advertise_id'], ['event', "event"], ['event_date', 'event_date']] )) %>
<%= text_field_tag "keyword" %>
<%= submit_tag "seach" %>
<% end %>

app/views/admin/informations/selected.html.erb
<table class="table">
<%= @informations%>
<tr>
<th>name</th>
<th>advertiser_id</th>
<th>email</th>
<th>phone</th>
<th>account</th>
<th>password</th>
<th>count</th>
</tr>
<% @information.each do |information| %>
<tr>

<td><%= information.information_id %></td>
<td><%= information.advertise_id %></td>


 <th><%= link_to 'Edit', edit_admin_advertiser_path(information) %></th>
 <th><%= button_to 'Delete', admin_advertiser_path(information), :method => :delete, :data => { :confirm => "Are you sure?" } %></th>
</tr>
<% end %>
</table>



 

app/views/admin/informations/show.html.erb
<table class="table">
<tr>
<th>name</th>
<th>advertiser_id</th>
<th>email</th>
<th>phone</th>
<th>account</th>
<th>password</th>
<th>count</th>
</tr>

<td><%= @advertises.id %></td>
<td><%= @advertises.email %></td>

</table>