config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :advertisers do
          collection do
              post :selected
          end
    end
    resources :advertises  do
         collection do
              post :selected           
        end
    end
    resources :advocates  do
         collection do
              post :selected           
        end
    end
    resources :tasks  do
         collection do
              post :selected           
        end
    end
    resources :informations   do
         collection do
              post :selected           
        end
    end
  end
  devise_for :advertisers
  resources :advertises

  resources :advocates
  resources :advertiseapis
  resources :beaconapis

  root to: redirect('/advertises')

end

app/models/advertise.rb
class Advertise < ActiveRecord::Base
	belongs_to :advertiser
end

app/models/advertiser.rb
class Advertiser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :advertises
end

app/models/advocate.rb
class Advocate < ActiveRecord::Base
end

app/models/information.rb
class Information < ActiveRecord::Base
end

app/models/message.rb
class Message < ActiveRecord::Base
end

app/models/task.rb
class Task < ActiveRecord::Base
end

app/controllers/advertiseapis_controller.rb
class AdvertiseapisController < ApplicationController
	 def index

		@advertises = Advertise.all.select("title","end_date_time","location")
		render :json =>@advertises
	end
   
end

app/controllers/advertises_controller.rb
class AdvertisesController < ApplicationController
before_action :authenticate_advertiser!  
	def index
		@advertise = Advertise.where(:advertiser_id => current_advertiser.id)
	end
       def new
              @advertise = Advertise.new
       end
	def create
  
             @advertise = Advertise.new(advertise_params)
             @advertise.advertiser_id = current_advertiser.id
             @advertise.save

             redirect_to :action => :index
      end
      def show
            @advertise = Advertise.find(params[:id])
      end
      def edit
      end

private
      def advertise_params
          
            params.require(:advertise).permit(:title, :content, :start_date_time, :end_date_time, :location, :max_number)


      end

end

app/controllers/advocates_controller.rb
class AdvocatesController < ApplicationController
	
	def index

		 @advocate=Advocate.find_by_account(params[:account])
		 if @advocate==nil
		 	render :json => Message.find_by_id(3)
		else
		 	
			if params[:password] == @advocate.password
		     
                             	 render :json => Message.find_by_id(1)
			else
		     	render :json => Message.find_by_id(2)

			end
		end
	end
	
	def create
		@advocate = Advocate.new(:name => params[:name],:account => params[:account],:password => params[:password],:email => params[:email],:phone => params[:phone])
		@advocate.save
	end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  #protect_from_forgery with: :exception
  #before_action :authenticate_advertiser!
end

app/controllers/beaconapis_controller.rb
class BeaconapisController < ApplicationController
end

app/controllers/information_controller.rb
class InformationController < ApplicationController
end

app/helpers/advertise_helper.rb
module AdvertiseHelper
end

app/helpers/advertiseapi_helper.rb
module AdvertiseapiHelper
end

app/helpers/advertiseapis_helper.rb
module AdvertiseapisHelper
end

app/helpers/advocate_helper.rb
module AdvocateHelper
end

app/helpers/advocates_helper.rb
module AdvocatesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beaconapis_helper.rb
module BeaconapisHelper
end

app/helpers/information_helper.rb
module InformationHelper
end

app/views/frameset/_admin_left.html.erb
<nav class="navbar navbar-left navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
   

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-left">
        <li> <%= link_to("advertiser", :controller => 'advertisers', :action => 'index') %> </li></br>
        <ul class="nav navbar-nav navbar-left">
        <li> <%= link_to("advertise",:controller => 'advertises', :action => 'index') %> </li></br>
          <ul class="nav navbar-nav navbar-left">
        <li> <%= link_to("advocate",:controller => 'advocates', :action => 'index') %> </li></br>
         <ul class="nav navbar-nav navbar-left">
        <li> <%= link_to("information",:controller => 'informations', :action => 'index') %> </li></br>
         <ul class="nav navbar-nav navbar-left">
        <li> <%= link_to("task",:controller => 'tasks', :action => 'index') %> </li></br>
    </ul>
    
      
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

   
  

app/views/frameset/_footer.html.erb
<footer class="container" style="margin-top: 100px;">
  <p class="text-center">Copyright ©2014 Rails101s
    <br>Design by <a href="http://sdlong.logdown.com" target=_new>sdlong</a>
  </p>
</footer>

app/views/frameset/_navbar_left.html.erb
  <ul class="nav nav-pills nav-stacked pull-left container-fluid">
  <% if advertiser_signed_in? %>  
    <li class="active"><%= link_to "Po廣告", :controller => '/advertises', :action => 'new' %></li><br>
    <li class="active"><%= link_to "廣告成效",:controller =>'/advertises', :action => 'index' %></li><br>
    <li class="active"><a href="/main/profile">基本資料</a></li>
    <% end %>
  </ul>

app/views/frameset/_navbar_top.html.erb
<nav class="navbar-form navbar-inverse " role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <a class="navbar-brand" href="/main/index">首頁</a>  
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li ><a class="navbar-brand" href="/main/test">什麼是行動廣告</a></li>
      </ul>
      <ul class="nav navbar-nav">
        <li ><a class="navbar-brand" href="#">最新訊息</a></li>
        </ul>
      <ul class="nav navbar-nav">
        <li ><a class="navbar-brand" href="#">成功案例</a></li>
        </ul>
      <ul class="nav navbar-nav">
        <li ><a class="navbar-brand" href="#">聯絡我們</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if advertiser_signed_in? %>  
      <li><%= link_to 'Edit profile', edit_advertiser_registration_path, :class => 'navbar-link' %> |</li>
      <li><%= link_to "Logout", destroy_advertiser_session_path, method: :delete, :class => 'navbar-link'  %></li>
  <% else %>
      <li><%= link_to "Sign up", new_advertiser_registration_path, :class => 'navbar-link'  %> |</li>
      <li><%= link_to "Login", new_advertiser_session_path, :class => 'navbar-link'  %></li>
  <% end %>
      </ul>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MobileAd</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <style>
#hh { 
  padding-left:300px; 
  padding-right:200px; 
  border: 1px solid 000000; 
}
#gg { 
  font-size: 22px;
  padding-top:80px; 
  padding-left:50px; 
  border: 1px solid 000000; 
}

</style>
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap-theme.min.css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="css/bootstrap.min.css" rel="stylesheet" media="screen">

  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <!-- 新 Bootstrap 核心 CSS 文件 -->
<link rel="stylesheet" href="//cdn.bootcss.com/bootstrap/3.3.5/css/bootstrap.min.css">

<!-- 可选的Bootstrap主题文件（一般不用引入） -->
<link rel="stylesheet" href="//cdn.bootcss.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">

<!-- jQuery文件。务必在bootstrap.min.js 之前引入 -->
<script src="//cdn.bootcss.com/jquery/1.11.3/jquery.min.js"></script>

<!-- 最新的 Bootstrap 核心 JavaScript 文件 -->
<script src="//cdn.bootcss.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

</head>
<body>
 <div class="container-fluid">
  <%= render "frameset/navbar_top" %>
 </div>
 <div class="container-fluid">
  <div id="gg">
   <%= render "frameset/navbar_left" %>
  </div>
  <div id="hh">
  <%= yield %>
</div>
 </div>
 <%= render "frameset/footer" %>  
</body>
</html>